[[main]]
identifier = "home"
name = "Home"
weight = -100
parent = ""
url = "/"

[[main]]
identifier = "directions"
name = "Directions"
weight = 100
parent = "about"
url = "/#directions"
pre = '<i class="fad fa-directions"></i>'

[[main]]
identifier = "latestnews"
name = "Latest News"
weight = 200
parent = "about"
url = "/#news"
pre = '<i class="fab fa-twitter"></i>'

[[main]]
identifier = "aboutrule01"
name = "-"
weight = 1000
parent = "about"

[[main]]
identifier = "classesrule01"
name = "-"
weight = 1000
parent = "classes"


