main:
  - identifier: about
    name: About
    url: /
    weight: 200
    post: Our facinating origins
  - identifier: contact
    name: Contact
    url: /
    weight: 300
    post: At your service
  - identifier: something
    name: Something
    url: /
    weight: 110
    post: This is something
    parent: about
