copyright = "Copyright &copy; 2022-2025 North Texas Aikido. All Rights Reserved."
logo = "/images/MON.svg"
logo_small = "/images/MON.svg"
cover = "https://picsum.photos/1050/450"
crafted_email_url = "mailto:Claycle <05_cod_chimp@icloud.com>?subject=Comment%20on%20North%20Texas%20Aikido"

[cascade.show]
pandemic = false
seminar = false
dojocho = true
welcome = true
