copyright = "Copyright &copy; 2022 North Texas Aikido. All Rights Reserved."
logo = "/image/MON.svg"
logo_small = "/image/MON.svg"
cover = "https://picsum.photos/1050/450"
crafted_email_url = "mailto:05_cod_chimp@icloud.com"
